# To change the visualized name of app use, package rename command: rename setAppName --targets ios,android,macos,windows,linux --value "Beauty Center"
name: beauty_center
description: "Management app for beauty centers with offline-first approach."
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State management
  flutter_riverpod: ^3.0.3

  # Local DB
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1

  # Remote backend
  supabase_flutter: ^2.10.3
  #flutter_cache_manager: ^3.4.1
  #cache_network_image: ^3.4.0

  # UI and theming
  flex_color_scheme: ^8.3.1
  flutter_screenutil: ^5.9.3
  material_symbols_icons: ^4.2874.0
  flex_color_picker: ^3.7.2
  flutter_animate: ^4.5.2
  syncfusion_flutter_datepicker: ^31.2.5
  #infinite_calendar_view: ^2.10.1
  #random_avatar: ^0.0.8
  #table_calendar: ^3.2.0
  #calendar_view: ^1.4.0
  #infinite_scroll_pagination
  #url_launcher: ^6.3.2
  #vibration: ^3.1.4

  # Navigation
  sidebarx: ^0.17.2
  google_nav_bar: ^5.0.7

  # Utils
  logging: ^1.3.0
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.4
  package_info_plus: ^9.0.0
  dio: ^5.9.0
  url_launcher: ^6.3.2
  pinput: ^5.0.2

  # Assets
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.3
  drift_dev: ^2.29.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/beauty_center_launcher_icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/icons/beauty_center_launcher_icon.png"
    icon_size: 256

flutter_native_splash:
  color: "#6750A4"
  color_dark: "#6750A4"
  image: "assets/icons/beauty_center_launcher_icon.png"
  android: true
  ios: false
  web: false
  android_gravity: center
  fullscreen: true
