# To change the visualized name of app use, package rename command: rename setAppName --targets ios,android,macos,windows,linux --value "Beauty Center"
name: beauty_center
description: "Management app for beauty centers with offline-first approach."
publish_to: 'none'
version: 0.1.3

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State management
  flutter_riverpod: ^3.0.3

  # Local DB
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1

  # UI and theming
  flex_color_scheme: ^8.3.0
  flutter_screenutil: ^5.9.3
  material_symbols_icons: ^4.2874.0
  flex_color_picker: ^3.7.1

  # Navigation
  sidebarx: ^0.17.2
  google_nav_bar: ^5.0.7

  # Utils
  logging: ^1.3.0
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.3
  drift_dev: ^2.28.3
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
  generate: true
